# Generated by Django 2.0.13 on 2019-03-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniurl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.AlterField(
            model_name='url',
            name='tiny_url',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
